name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

      - uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7  # stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5  # v2

      - name: Format check
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test

      - name: Doc
        run: cargo doc --no-deps

      - name: Dependency policy check
        run: cargo deny check

      - name: Vulnerability audit
        run: cargo install cargo-audit --locked && cargo audit
